### ISSUE TITLE
Issue: webhook not used

### ISSUE THREAD

**Issue by benchonaut** [muety/telepush#53]
* current docker image ( ghcr -> muety -> telepush)
* tried to set secretUrl for setWebhook, thingy did still want me to send `/api/updates` .. inacceptable (!)
* from the go code it should be 
   `/api/updates_YOURcustomTOKEN`
   (    the default is `/api/updates` , just if any one googles this   )

* since the thingy did not show the message from source code ( currently LINE 138 , `Updates from Telegram are accepted under '/api%s'. Set the webhook accordingly (see https://core.telegram.org/bots/api#setwebhook)\n", botConfig.GetUpdatesPath(` ) 
   nginx was (ab)used and curl was used to set the webhook

---

relevant parts (nginx):

```
location /api/ {

    location = /api/updates {
        deny all; return 403;
    }
    location ~ ^/api/messages$ {
         return 404;
         access_log /dev/null;
    }

      location = /api/updates_customstring {
      rewrite  ^/api/updates_customstring$ /api/updates break;
      client_max_body_size 4M;

      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_cache_bypass $http_upgrade;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
      proxy_pass http://upstream_signals ;
      proxy_set_header Host $host;
      proxy_redirect     off;

      }
}
```

relevant parts(curl)

```
# clear webhook
curl -F "url=" https://api.telegram.org/bot<YOURTOKEN>/setWebhook
curl -F "url=https://<YOURDOMAIN.EXAMPLE>/api/updates_customstring" https://api.telegram.org/bot<YOURTOKEN>/setWebhook

```
---
## Your Question was ? 

* why is the thingy not using the setUrl parameter ( used in docker compose: `APP_URL_SECRET: customtokenthingy`)
* are PR's welcome to document at least the /api/updates endpoint ?

regards

**Comment by muety** [comment]
Sorry, I think I can't reproduce this. Everything working fine for me.

```bash
ferdinand@ferdinand:/tmp$ docker run -it --rm -e APP_TOKEN=foo -e APP_URL_SECRET=bar ghcr.io/muety/telepush
2023/05/09 20:26:38 error: failed to read store from /srv/data/store.gob
2023/05/09 20:26:38 Read existing gob store from file
2023/05/09 20:26:38 Environment: production
2023/05/09 20:26:38 Version: 3.3.1
2023/05/09 20:26:38 Using webhook mode
2023/05/09 20:26:38 Updates from Telegram are accepted under '/api/updates_bar'. Set the webhook accordingly (see https://core.telegram.org/bots/api#setwebhook)
2023/05/09 20:26:38 Listening for HTTP on 0.0.0.0:8080.
```

Can you show your compose file?

**Comment by benchonaut** [comment]
(
 update: the image was re-tagged on the local machine , so it was effectively using the old webhook2telegram,
 so at least the endpoint issue is "solved" for the current version,

 so why was it re-tagged / down-graded ?

main problem with with the "real current" image: if sending the  the suggested "default" json
```
curl -XPOST -H 'Content-Type: application/json'      -d '{ "text": "another_test_tokURL_default *Hello World!* (yes, this is Markdown)" }' https://my-custom-url.tld/api/messages/Your-Tic-Tac-Token
```

the thingy returns 
```
2023/05/09 21:12:46 error: telegram api returned status 400: 'Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 38' 
```

this is why the "older" version is in place at this point  , markdown parsing breaks even with the example 

)

compose.yml is "normal"
```
version: '3'

services:
  webhook2telegram:
#    image: n1try/webhook2telegram
#    image: ghcr.io/muety/webhook2telegram:latest
    image: ghcr.io/muety/telepush
    container_name: ${APP_URL}
    hostname: ${APP_URL}
    restart: unless-stopped
#    working_dir: /var/www/html
    volumes:
      - ${STORAGE_ROOT:-/storage_global/data/}/${APP_URL}/botdata:/srv/data
    env_file:
        - .env
    command:    /bin/ash -c "apk add grep ; /bin/sh /app/entrypoint.sh 2>&1 | grep --line-buffered -v -e 'polling for updates' -e 'got unknown command' "
    entrypoint: /bin/ash -c "apk add grep ; /bin/sh /app/entrypoint.sh 2>&1 | grep --line-buffered -v -e 'polling for updates' -e 'got unknown command' "
    environment:
      VIRTUAL_HOST: ${APP_URL}
      VIRTUAL_PORT: 8080
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: ${APP_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL_POLICY: Mozilla-Modern
      SSH_PORT: ${SSH_PORT}
      APP_MODE: ${APP_MODE:-webhook}
      APP_TOKEN: ${APP_TOKEN:-YouHaveToSetYourToken}
      APP_URL_SECRET: ${APP_URL_SECRET:-incomingtgwebhookting}
    ports:
#      - ${SSH_PORT:-0}:22
      - "127.0.0.1:${LOCAL_PORT:-55553}:8080/tcp"
    logging:
      driver: ${DOCKER_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-20m}
        max-file: ${DOCKER_LOG_MAX_FILE:-10}

networks:
  default:
    external:
      name: ${NGINX_NETWORK:-nginx-proxy}
```
