### ISSUE TITLE
Add request option to disable parsing text as Markdown

### ISSUE THREAD

**Issue by muety** [muety/telepush#67]
When a message contains reserved Markdown characters without actually being Markdown (e.g. a single `_`, a single `[`, etc.). Telegram will respond with an error. 

```
'Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 20'
```

There should be a request option so that suers can explicitly disable Markdown.

**Comment by darkfessing** [comment]
Thx) Just updated my telepush and tried again. Looks like I've received new/old error?

Alertmanager:
`ts=2023-12-28T23:49:28.953Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://1.1.X.XXX:8080/api/inlets/alertmanager/XXXXXX?disable_markdown=true&disable_link_previews=true: telegram api returned status 400: 'Bad Request: message is too long'\n"`

Telepush:
`2023/12/28 23:49:28 error: telegram api returned status 400: 'Bad Request: message is too long'`

I guess new query options ignores "-truncateMsgs true"?

Telepush deployed locally by:
```
docker run -it -d \
    -p 8080:8080 \
    -v telepush_data:/srv/data \
    --name telepush \
    darkfess/telepush \
    -mode poll \
    -token xxxxxxxxxxxxxxxxx \
    -truncateMsgs true
```

**Comment by muety** [comment]
Sorry, found another little bug in the truncation. Please try if the latest fix works for you (didn't push a new release / new Docker, yet).

**Comment by darkfessing** [comment]
Thank you, looks like everything is fine now.

BTW I`ve also resolved my problem with pretty-Markdown notifications. As I mentioned my error here: https://github.com/muety/telepush/issues/66#issuecomment-1871471760 (some hell happening with link after "Source: ...")

Solution (externalURL):

```
  config:
    global:
    route:
      group_by: ['namespace','alertname', 'instance', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'telepush'
    receivers:
    - name: 'telepush'
      webhook_configs:
        - url: 'http://1.1.X.XXX:XXXX/api/inlets/alertmanager/XXXXXX?disable_markdown=false&disable_link_previews=true'
          http_config:
  **externalURL: ''**
```

This disables "Source:" in notifications text (that means no problems with Markdown).
